/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital;

import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Casa
 */
public class DAlta extends javax.swing.JFrame {

    String ruta = "C:\\Users\\SSS\\Documents\\NetBeansProjects\\Hospital\\src\\Archivo\\Datos.txt";

    public DAlta() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        bPacientes = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        bHab = new javax.swing.JButton();
        bVDatos = new javax.swing.JButton();
        Panel = new javax.swing.JTextArea();
        UserIcon = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BAtras = new javax.swing.JButton();
        BDAlta = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        bPacientes.setText("Habitaciones");
        bPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPacientesActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Dar de alta");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bHab.setText("Habitaciones");
        bHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHabActionPerformed(evt);
            }
        });
        jPanel1.add(bHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 123, -1));

        bVDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        bVDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVDatosActionPerformed(evt);
            }
        });
        jPanel1.add(bVDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 30, 28));

        Panel.setEditable(false);
        Panel.setColumns(20);
        Panel.setRows(5);
        jPanel1.add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 110));

        UserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar pac.png"))); // NOI18N
        jPanel1.add(UserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 80, -1));

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDKeyTyped(evt);
            }
        });
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 150, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        BAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Casa.png"))); // NOI18N
        BAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(BAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 40, 30));

        BDAlta.setText("Dar de alta");
        BDAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDAltaActionPerformed(evt);
            }
        });
        jPanel1.add(BDAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 100, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel5.setText("Ingrese el ID del paciente");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 200, -1));

        Fondo.setBackground(new java.awt.Color(0, 0, 0));
        Fondo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1.jpg"))); // NOI18N
        Fondo.setPreferredSize(new java.awt.Dimension(350, 400));
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void BDAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDAltaActionPerformed

        Metodos m = new Metodos();

        String IdB = txtID.getText();

        if (!txtID.getText().isEmpty()) {
            if (m.buscarLineaPorId(ruta, IdB) == -1) {
                JOptionPane.showMessageDialog(null, "ID no existe o no está registrado");
            } else {
                int p = JOptionPane.showConfirmDialog(null, "Está seguro de que quiere dar de alta a este paciente?");
                if (p == 0) {
                    m.eliminarLinea(ruta, m.buscarLineaPorId(ruta, IdB));

                    JOptionPane.showMessageDialog(null, "El paciente ha sido dado de alta");

                    Panel.setText("");
                } else {

                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese un ID");
        }
    }//GEN-LAST:event_BDAltaActionPerformed

    private void bVDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVDatosActionPerformed
        Mhabitaciones m = new Mhabitaciones();

        Panel.setText("");

        boolean v = false;
        String IdB = txtID.getText();

        if (!txtID.getText().isEmpty()) {

            int n = contarFilas(ruta);

            String resultado = "";

            for (int i = 0; i < n; i++) {
                if (m.Pacientes[i][2].equals(IdB)) {
                    resultado += "Nombre: " + m.Pacientes[i][0] + "\n";
                    resultado += "Apellido: " + m.Pacientes[i][1] + "\n";
                    resultado += "Identificación: " + m.Pacientes[i][2] + "\n";
                    resultado += "Código de Habitación: " + m.Pacientes[i][3] + "\n";
                    v = false;
                    Panel.append(resultado);
                    break;
                } else {
                    v = true;
                }
            }

            if (v) {
                JOptionPane.showMessageDialog(null, "No se encontraron coincidencias");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese el ID");
        }

    }//GEN-LAST:event_bVDatosActionPerformed

    private void txtIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyTyped
        int key = evt.getKeyCode();

        if (txtID.getText().length() == 15) {
            evt.consume();
        }

    }//GEN-LAST:event_txtIDKeyTyped

    private void BAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAtrasActionPerformed
        VPrinc vp = new VPrinc();

        vp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BAtrasActionPerformed

    private void bPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPacientesActionPerformed
        Habitaciones hab = new Habitaciones();

        hab.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_bPacientesActionPerformed

    private void bHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHabActionPerformed
        Habitaciones hab = new Habitaciones();

        hab.setVisible(true);

        this.dispose();

    }//GEN-LAST:event_bHabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DAlta().setVisible(true);
            }
        });
    }

    public static int contarFilas(String nombreArchivo) {
        int numFilas = 0;
        try {
            BufferedReader lector = new BufferedReader(new FileReader(nombreArchivo));
            while (lector.readLine() != null) {
                numFilas++;
            }
            lector.close();
        } catch (IOException e) {
            System.out.println("Error al leer el archivo " + nombreArchivo + ": " + e.getMessage());
        }
        return numFilas;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAtras;
    private javax.swing.JButton BDAlta;
    private javax.swing.JLabel Fondo;
    private javax.swing.JTextArea Panel;
    private javax.swing.JLabel UserIcon;
    private javax.swing.JButton bHab;
    private javax.swing.JButton bPacientes;
    private javax.swing.JButton bVDatos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
