/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital;

import static hospital.Registro.registros;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Casa
 */
public class EliminarUser extends javax.swing.JFrame {

    String ruta = "C:\\Users\\SSS\\Documents\\NetBeansProjects\\Hospital\\src\\Archivo\\usuarios.txt";

    public EliminarUser() {
        initComponents();
        
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bVDatos = new javax.swing.JButton();
        Panel = new javax.swing.JTextArea();
        UserIcon = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BDAlta = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eliminar usuarios");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bVDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        bVDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVDatosActionPerformed(evt);
            }
        });
        jPanel1.add(bVDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 30, -1));

        Panel.setEditable(false);
        Panel.setColumns(20);
        Panel.setRows(5);
        jPanel1.add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, 120));

        UserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminar user.png"))); // NOI18N
        jPanel1.add(UserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 80, -1));

        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserKeyTyped(evt);
            }
        });
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 150, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Usuario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        BDAlta.setText("Eliminar");
        BDAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDAltaActionPerformed(evt);
            }
        });
        jPanel1.add(BDAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 100, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel5.setText("Ingrese el nombre de usuario");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 230, -1));

        Fondo.setBackground(new java.awt.Color(0, 0, 0));
        Fondo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1.jpg"))); // NOI18N
        Fondo.setPreferredSize(new java.awt.Dimension(350, 400));
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void BDAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDAltaActionPerformed
         Metodos m = new Metodos();
        Registro r = new Registro();
            
        String UsB = txtUser.getText();
        
        if(!txtUser.getText().isEmpty()){
            int p = JOptionPane.showConfirmDialog(null, "Está seguro de que quiere eliminar este Usuario?");
        
        if(p==0){
        m.buscarLineaPorId(ruta, UsB);

        m.eliminarLinea(ruta, m.buscarLineaPorId(ruta, UsB));
        
        JOptionPane.showMessageDialog(null, "El usuario ha sido eliminado");
        
        r.mostrarMatriz(r.Musers);
        
        Panel.setText("");
        }else{
            
        }
        }else{
           JOptionPane.showMessageDialog(null, "Ingrese un ID"); 
        }
        
        
    }//GEN-LAST:event_BDAltaActionPerformed

    private void bVDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVDatosActionPerformed
        Mhabitaciones m = new Mhabitaciones();
        Registro r = new Registro();

        Panel.setText("");

        boolean v = false;
        String UsB = txtUser.getText();
if(!txtUser.getText().isEmpty()){
        int n = contarFilas(ruta);

        String resultado = "";

        for (int i = 0; i < n; i++) {
            if (r.Musers[i][2].equals(UsB)) {
                resultado += "Nombre: " + r.Musers[i][0]+"\n";
                resultado += "Id: " + r.Musers[i][1]+"\n";
                resultado += "Usuario: " + r.Musers[i][2]+"\n";
                resultado += "Contraseña: " + r.Musers[i][3]+"\n";
                resultado += "Tipo: " + r.Musers[i][4]+"\n";
                v = false;
                Panel.append(resultado);
                break;
            } else {
                v = true;
            }
        }

        if (v) {
            JOptionPane.showMessageDialog(null, "No se encontraron coincidencias");
        }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese un ID");
        }
        


    }//GEN-LAST:event_bVDatosActionPerformed

    private void txtUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyTyped
        int key = evt.getKeyCode();

        if (txtUser.getText().length() == 15) {
            evt.consume();
        }

    }//GEN-LAST:event_txtUserKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarUser().setVisible(true);
            }
        });
    }

    public static int contarFilas(String nombreArchivo) {
        int numFilas = 0;
        try {
            BufferedReader lector = new BufferedReader(new FileReader(nombreArchivo));
            while (lector.readLine() != null) {
                numFilas++;
            }
            lector.close();
        } catch (IOException e) {
            System.out.println("Error al leer el archivo " + nombreArchivo + ": " + e.getMessage());
        }
        return numFilas;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BDAlta;
    private javax.swing.JLabel Fondo;
    private javax.swing.JTextArea Panel;
    private javax.swing.JLabel UserIcon;
    private javax.swing.JButton bVDatos;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
