/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital;

import static hospital.Registro.registros;
import javax.swing.JOptionPane;

/**
 *
 * @author Casa
 */
public class VPrinc extends javax.swing.JFrame {

    /**
     * Creates new form VPrinc
     */
    public VPrinc() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bHab = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        RegistroU = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bDAlta = new javax.swing.JButton();
        bCS = new javax.swing.JButton();
        bPacientes = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana principal");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bHab.setText("Habitaciones");
        bHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHabActionPerformed(evt);
            }
        });
        jPanel2.add(bHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 123, -1));

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });
        jPanel2.add(bSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 123, -1));

        RegistroU.setText("Registrar usuarios");
        RegistroU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroUActionPerformed(evt);
            }
        });
        jPanel2.add(RegistroU, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 123, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Opciones");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 77, -1, -1));

        bDAlta.setText("Dar de alta");
        bDAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDAltaActionPerformed(evt);
            }
        });
        jPanel2.add(bDAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 123, -1));

        bCS.setText("Cerrar sesion");
        bCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCSActionPerformed(evt);
            }
        });
        jPanel2.add(bCS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 123, -1));

        bPacientes.setText("Pacientes");
        bPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPacientesActionPerformed(evt);
            }
        });
        jPanel2.add(bPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 123, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 370));

        Fondo.setBackground(new java.awt.Color(0, 0, 0));
        Fondo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1.jpg"))); // NOI18N
        Fondo.setPreferredSize(new java.awt.Dimension(350, 400));
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHabActionPerformed
        Habitaciones hab = new Habitaciones();

        hab.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_bHabActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed

        int n = JOptionPane.showConfirmDialog(null, "Está seguro que quiere cerrar el programa?");

        if (n == 0) {
            System.exit(0);
        } else {

        }

    }//GEN-LAST:event_bSalirActionPerformed

    private void RegistroUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroUActionPerformed
        Registro r = new Registro();
        Metodos m = new Metodos();

        if (m.getAdmin().equals("true")) {
            r.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Acceso denegado");
        }

    }//GEN-LAST:event_RegistroUActionPerformed

    private void bDAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDAltaActionPerformed
        DAlta da = new DAlta();

        da.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_bDAltaActionPerformed

    private void bCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCSActionPerformed
        LoginNuevo ln = new LoginNuevo();

        int n = JOptionPane.showConfirmDialog(null, "Está seguro que quiere cerrar la sesion?");

        if (n == 0) {
            ln.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_bCSActionPerformed

    private void bPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPacientesActionPerformed
        Mhabitaciones mh = new Mhabitaciones();

        mh.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bPacientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPrinc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton RegistroU;
    private javax.swing.JButton bCS;
    private javax.swing.JButton bDAlta;
    private javax.swing.JButton bHab;
    private javax.swing.JButton bPacientes;
    private javax.swing.JButton bSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
